view: config
id: module_custom_html

fields:

  content:
    component: cmseditor
    params:
      span: 2
      height: 500px
      copyFrom: contentPlain
      showLabel: false
      
  templateEngine:
       component: typeSelector
       params:
            typeExtensionClass: tools.dynamia.cms.core.StringParser
      
