id: CMSConfig
view: config

fields:
    SuperAdminSite:
        component: superAdminSite
        description: Admin Site with full system access

    HomePath:
        label: Home Path
        component: directorybox
        description: Application Home Folder
        
    DefaultTemplate:
        component: templateSelector
        description: Default Site Template
        
        
layout:
    columns: 1