id: CMSConfig
view: config

fields:
    SuperAdminSite:        
        label: Admin Site
        description: Admin Site with full system access

    HomePath:
        label: Home Path        
        description: Application Home Folder
        
    DefaultTemplate:
        component: templateSelector
        description: Default Site Template
        
        
layout:
    columns: 2