view: form
beanClass: tools.dynamia.cms.site.shoppingcart.domain.ShoppingSiteConfig
autofields: false

fields:
  paymentGatewayId:
    label: Gateway ID
  paymentGatewayName:
    label: Gateway Name
  paymentEnabled:
  allowEmptyPayment:
  billingAddressRequired:
  shippingAddressRequired:
  
  minPaymentAmount:
  maxPaymentAmount:
  shipmentPercent:
    component: decimalbox
  minShipmentAmount:
  defaultCurrency:
  autoSendOrders:
  orderSenderURL:
  
  descriptionTemplate:
  notificationEmails:
    description: You can use multiple emails address separated by comma
  orderCompletedMailTemplate:
  orderShippedMailTemplate:
  notificationMailTemplate:
  mailAccount:
  

groups:
    values:
       fields:
       - minPaymentAmount
       - maxPaymentAmount
       - shipmentPercent
       - minShipmentAmount
    notifications:
       fields:
       - notificationEmails  
       - orderCompletedMailTemplate
       - orderShippedMailTemplate
       - notificationMailTemplate
       - mailAccount  
  
 
layout:
  columns: 2
