view: form
beanClass: com.dynamia.cms.site.shoppingcart.domain.ShoppingSiteConfig
autofields: false

fields:
  paymentGatewayId:
    label: Gateway ID
  paymentGatewayName:
    label: Gateway Name
  paymentEnabled:
  minPaymentAmount:
  defaultCurrency:
  descriptionTemplate:
  notificationEmails:
    description: You can use multiple emails address separated by comma
  orderCompletedMailTemplate:
  orderShippedMailTemplate:
  notificationMailTemplate:
  mailAccount:
  

groups:
    notifications:
       fields:
       - notificationEmails  
       - orderCompletedMailTemplate
       - orderShippedMailTemplate
       - notificationMailTemplate
       - mailAccount  
  
 
layout:
  columns: 2
