view: crud
beanClass: com.dynamia.cms.site.shoppingcart.domain.ShoppingSiteConfig
controller: com.dynamia.cms.admin.shopping.controllers.ShoppingSiteConfigController
autofields: false


actions:
  NewAction:
    enabled: false
  
  DeleteAction:
    enabled: false