view: table
beanClass: tools.dynamia.cms.site.shoppingcart.domain.ShoppingSiteConfig
autofields: false

fields:
  paymentGatewayId:
    label: Gateway ID
  paymentGatewayName:
    label: Gateway Name
  paymentEnabled:
  minPaymentAmount:
  maxPaymentAmount:
  shipmentPercent:
  defaultCurrency:
  descriptionTemplate:
  notificationEmails:
  orderCompletedMailTemplate:
  orderShippedMailTemplate:
  notificationMailTemplate:
  mailAccount:
 
layout:
  columns: 2
