view: config
id: module_products_carousel

fields:

  type:
    component: enumbox
    required: true
    params:
      enumClass: tools.dynamia.cms.products.modules.ProductCarouselType
      valuesAsString: true


  category:
    component: entitypicker
    params:
      entityClass: tools.dynamia.cms.products.domain.ProductCategory

  status:
    description: Only for CUSTOM type

  status2:
    description: Only for CUSTOM type
    params:
      placeholder: Alternate status value


  columns:

  orderBy:
    component: enumbox
    params:
      enumClass: tools.dynamia.cms.products.modules.ProductOrderField
      valuesAsString: true
  pageSize:
    
