view: config
id: module_products_categories

fields:            


  brand:
    label: Brand (optional)
    component: entitypicker
    params:
      entityClass: tools.dynamia.cms.site.products.domain.ProductBrand
      
  parentCategory:
    label: Parent Category (optional)
    component: entitypicker
    params:
      entityClass: tools.dynamia.cms.site.products.domain.ProductCategory
 
    
