view: table
beanClass: tools.dynamia.cms.payment.domain.PaymentGatewayConfig
autofields: false

fields:

  label:
    label: Parameter
    params:
      header:
        width: 150px

  value:
    component: textbox
    params:
      width: 400px

 
 
  