view: form
beanClass: tools.dynamia.cms.shoppingcart.domain.ShoppingSiteConfig
autofields: false

fields:
  paymentGatewayAccount:
    component: combobox
    params:
      automodel: true

  minPaymentAmount:
  maxPaymentAmount:
  shipmentPercent:
    component: decimalbox
  minShipmentAmount:
  defaultCurrency:
  paymentTypes:


  orderSenderURL:
    label: Order Sender URL
  orderStatusURL:
    label: Order Status URL


  paymentsSenderURL:
    label: Payments Sender URL

  descriptionTemplate:
  paymentDisabledMessage:
    params:
      span: 4


  paymentEnabled:
  allowEmptyPayment:

  billingAddressRequired:
  shippingAddressRequired:

  autoSendPayments:
  autoSendOrders:

  notificationEmails:
    description: You can use multiple emails address separated by comma
  orderCompletedMailTemplate:
  orderShippedMailTemplate:
  notificationMailTemplate:
  mailAccount:
  minQuantityByProducts:
  minQuantityByCart:

  parameters:
    component: crudview
groups:
  values:
    fields:
    - minPaymentAmount
    - maxPaymentAmount
    - shipmentPercent
    - minShipmentAmount
    - minQuantityByProducts
    - minQuantityByCart
  remote:
  - orderSenderURL
  - orderStatusURL
  - paymentsSenderURL
  - autoSendOrders
  - autoSendPayments
  notifications:
    fields:
    - notificationEmails
    - orderCompletedMailTemplate
    - orderShippedMailTemplate
    - notificationMailTemplate
    - mailAccount


layout:
  columns: 4
