view: form
beanClass: tools.dynamia.cms.products.domain.ProductCategory
autofields: false

fields:

  parent:
  name:
  alternateName:
  alias:
  relatedCategory:
  template:
    description: Product Template

  alternateTemplate:
    description: Product Alternate Template
  tags:
    parms:
      placeholder: separted by comma
      span: 4
  description:
    params:
      multiline: true
      height: 100px
      span: 4

  order:
  externalRef:
  virtual:
  active:

  details:
    component: crudview
layout:
  columns: 4