view: form
beanClass: tools.dynamia.cms.products.domain.ProductTemplate
autofields: false

fields:
  
    name:   
    templateEngine:
       label: Engine
       component: typeSelector
       params:
            typeExtensionClass: tools.dynamia.cms.core.StringParser
    enabled:
    description:
       params:
          multiline: true
          span: 3
          height: 100px
    content:
        component: cmseditor
        params:
            unescape: true
            span: 3
            height: 400px
    
   

layout:
    columns: 3