view: table
beanClass: tools.dynamia.cms.products.domain.ProductDetail
autofields: false

fields:    
    name:
        params:
            span: 2
    value:
    description:       
    featured:    
    imageURL:
        label: Image URL
