view: config
id: module_banner_sliders


fields:    
    category:
        component: entitypicker
        params:
            entityClass: tools.dynamia.cms.site.banners.domain.BannerCategory
        
