view: table
beanClass: tools.dynamia.cms.site.products.domain.ProductCreditPrice
autofields: false

fields:
  
    number:
    price:
        params:
            converter: converters.Currency
            header:
                align: right
            
    description:
