view: form
beanClass: com.dynamia.cms.site.products.domain.ProductDetail
autofields: false

fields:
  
    name:
        params:
            span: 2
    value:
    description:       
    featured:
    order:
    imageURL:
        label: Image URL
        component: resourceSelector
        params:
            span: 2
    
    
   

layout:
    columns: 2