view: form
beanClass: com.dynamia.cms.site.products.domain.ProductBrand
autofields: false

fields:
  
    name:
    website:
    description:
       params:
          multiline: true
          span: 2
          height: 100px
    image:
    
    
   

layout:
    columns: 2