view: form
beanClass: com.dynamia.cms.site.products.domain.ProductsSiteConfig
hidden: [id,lastSync,token,parametersAsMap]
sortFields: [site,pricePattern,defaultCurrency,productsPerPage,productsStockToShow,showEnabled,quoteEnabled, datasourceURL,datasourceImagesURL,datasourceBrandImagesURL,datasourceStoreImagesURL,datasourceUsername,datasourcePassword]

fields:
    
    site:
        params:
            span: 2
            
    
    datasourceURL:
        label: URL
    
    datasourceImagesURL:
        label: Images URL
        
    datasourceBrandImagesURL:
        label: Brands Images URL
    
    datasourceStoreImagesURL:
        label: Stores Images URL
    
    datasourceUsername:
        label: Username
    
    datasourcePassword:
        label: Password
        
                
    parameters:
        component: crudview
    
groups:
    
    general:
        label: Basic Settings
        fields: [site,pricePattern,defaultCurrency,productsPerPage,productsStockToShow,shopEnabled,quoteEnabled]
            
    
    datasource:
        label: Datasource Settings
        fields: [datasourceURL,datasourceImagesURL,datasourceBrandImagesURL,datasourceStoreImagesURL,datasourceUsername,datasourcePassword]
        
layout:
    columns: 2