view: form
beanClass: tools.dynamia.cms.site.products.domain.ProductsSiteConfig
hidden: [id,lastSync,token,parametersAsMap]
sortFields: [pricePattern,defaultCurrency,productsPerPage,productsStockToShow,synchronizationEnabled,showEnabled,quoteEnabled,showBadges, datasourceURL,datasourceImagesURL,datasourceBrandImagesURL,datasourceStoreImagesURL,datasourceStoreContactImagesURL,datasourceUsername,datasourcePassword,mailAccount,shareProductMailTemplate,orderCompletedMailTemplate]

fields:            
    
    datasourceURL:
        label: URL
    
    datasourceImagesURL:
        label: Images URL
        
    datasourceBrandImagesURL:
        label: Brands Images URL
    
    datasourceStoreImagesURL:
        label: Stores Images URL
        
    datasourceStoreContactImagesURL:
        label: Stores Contacts Images URL
    
    datasourceUsername:
        label: Username
    
    datasourcePassword:
        label: Password
                        
    parameters:
        component: crudview
  
  
    mailAccount:
        label: Account   
   
   
    shareProductMailTemplate:   
        label: Share Product Template
   
    orderCompletedMailTemplate:   
        label: Order Completed Template
        
    synchronizationEnabled:
        label: Enabled
        
    priceUserGroup:
      label: Price
    price2UserGroup:
      label: Price 2
    costUserGroup:
      label: Cost
groups:
    
    general:
        label: Basic Settings
        fields: [site,pricePattern,defaultCurrency,productsPerPage,productsStockToShow,shopEnabled,quoteEnabled,showBadges,minStock]
            
    priceUsersGroups:
        fields: [priceUserGroup,price2UserGroup,costUserGroup]
    
    datasource:
        label: Datasource Settings
        fields: [datasourceURL,datasourceImagesURL,datasourceBrandImagesURL,datasourceStoreImagesURL,datasourceStoreContactImagesURL,datasourceUsername,datasourcePassword]
    
    synchronization:
        fields: [synchronizationEnabled, syncProductImages,syncProductDetails, syncStockDetails, syncProductCreditPrices, syncStoreContacts]
    
    email:
        label: Mail Settings
        fields: [mailAccount,shareProductMailTemplate,orderCompletedMailTemplate]
        
layout:
    columns: 3