view: form
beanClass: com.dynamia.cms.site.products.domain.ProductCategory
hidden: [id,externalRef]
sortFields: [parent,name,alias,description,active]

fields:
  
    
    parent:
        component: label
    
    template:
        description: Product Template
       
        
    description:
        params:
            multiline: true
            height: 200px
            span: 2
    
   

layout:
    columns: 2