view: table
beanClass: com.dynamia.cms.site.products.domain.ProductsSiteConfig
hidden: [id,datasourcePassword,parametersAsMap,datasourceStoreImagesURL,datasourceImagesURL,datasourceBrandImagesURL,datasourcePassword]
sortFields: [site,lastSync,datasourceURL,datasourceUsername,defaultCurrency,pricePattern,productsPerPage,productsStockToShow,token]

fields:
    datasourceURL:
        label: URL
    
    datasourceImagesURL:
        label: Images URL
    
    datasourceUsername:
        label: Username
        
    lastSync:
        nullValue: none
