view: table
beanClass: com.dynamia.cms.site.products.domain.Product
autofields: false

fields:
   sku:
   
   name:
   brand:
   category:
   template:
   price:
      params:      
          converter: converters.Integer
          header:
             align: right
   lastPrice:
      params:
          converter: converters.Integer
          header:
             align: right
   storePrice:
      params:
          converter: converters.Integer
          header:
             align: right
   stock:
      params:
         header:
            align: center
   views:
      params:
         header:
            align: center
   active:
   featured:
   sale:
   newproduct:
      label: New
   status:
   promoEnabled:
       label: Promo
   promoValue:
       label: Value
   promoValueType:
       label: Type
   promoStartDate:
       label: Start Date
       params:
           converter: converters.Date
   promoEndDate:
       label: End Date
       params:
           converter: converters.Date
   