view: crud
beanClass: com.dynamia.cms.site.products.domain.ProductCategory
dataSetView: tree
parentName: parent
controller: com.dynamia.cms.admin.products.controllers.ProductCategoryTreeCrudController