view: table
beanClass: com.dynamia.cms.site.products.domain.ProductsSiteConfig
hidden: [id,datasourcePassword,parametersAsMap]
sortFields: [site,lastSync,datasourceURL,datasourceImagesURL,datasourceBrandImagesURL,datasourceUsername,datasourcePassword,defaultCurrency,pricePattern,productsPerPage,productsStockToShow,token]

fields:
    datasourceURL:
        label: URL
    
    datasourceImagesURL:
        label: Images URL
    
    datasourceUsername:
        label: Username
        
    lastSync:
        nullValue: none
        
    datasourceBrandImagesURL:
        label: Brands Images URL