view: tree
beanClass: tools.dynamia.cms.site.products.domain.ProductCategory
autofields: false


fields:
    id:
    name:
    relatedCategory:
       label: Related
    description:
    template:
        description: Product Template    
    alternateTemplate:
    active:
