view: form
beanClass: com.dynamia.cms.site.products.domain.ProductsSiteConfig
hidden: [id,lastSync,token,parametersAsMap]
sortFields: [pricePattern,defaultCurrency,productsPerPage,productsStockToShow,synchronizationEnabled,showEnabled,quoteEnabled,showBadges, datasourceURL,datasourceImagesURL,datasourceBrandImagesURL,datasourceStoreImagesURL,datasourceUsername,datasourcePassword,mailAccount,shareProductMailTemplate,orderCompletedMailTemplate]

fields:            
    
    datasourceURL:
        label: URL
    
    datasourceImagesURL:
        label: Images URL
        
    datasourceBrandImagesURL:
        label: Brands Images URL
    
    datasourceStoreImagesURL:
        label: Stores Images URL
    
    datasourceUsername:
        label: Username
    
    datasourcePassword:
        label: Password
                        
    parameters:
        component: crudview
  
  
    mailAccount:
        label: Account   
   
   
    shareProductMailTemplate:   
        label: Share Product Template
   
    orderCompletedMailTemplate:   
        label: Order Completed Template
groups:
    
    general:
        label: Basic Settings
        fields: [site,pricePattern,defaultCurrency,productsPerPage,productsStockToShow,synchronizationEnabled,shopEnabled,quoteEnabled,showBadges,minStock]
            
    
    datasource:
        label: Datasource Settings
        fields: [datasourceURL,datasourceImagesURL,datasourceBrandImagesURL,datasourceStoreImagesURL,datasourceUsername,datasourcePassword]
    
    email:
        label: Mail Settings
        fields: [mailAccount,shareProductMailTemplate,orderCompletedMailTemplate]
        
layout:
    columns: 2