view: form
beanClass: tools.dynamia.cms.site.products.domain.ProductCategory
autofields: false

fields: 
    
    parent:
        component: label        
    name:
    alternateName:
    alias:
    relatedCategory:    
    template:
        description: Product Template   
    
        
    description:
        params:
            multiline: true
            height: 100px
            span: 3
    
    order:
layout:
    columns: 3