view: form
beanClass: tools.dynamia.cms.site.products.domain.ProductBrand
autofields: false

fields:
  
    name:
    website:
    description:
       params:
          multiline: true
          span: 2
          height: 100px
    image:
       component: resourceUploadlink
       params:
           subfolder: products/brands/images
           generateFileName: true
       
    
    
   

layout:
    columns: 2