view: form
beanClass: tools.dynamia.cms.site.products.domain.ProductCategory
autofields: false

fields: 
    
    parent:        
    name:
    alternateName:
    alias:
    relatedCategory:    
    template:
        description: Product Template   
    
    alternateTemplate:
        description: Product Alternate Template   
        
    description:
        params:
            multiline: true
            height: 100px
            span: 4
    
    order:
    active:
    
    details:
      component: crudview
layout:
    columns: 4