view: form
beanClass: tools.dynamia.cms.site.products.domain.ProductReview
autofields: false

fields:
  user:
  stars:
  incomplete:
  comment:
    params:
      span: 3

layout:
  columns: 3